/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.warehouse_management;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author lyeschl
 */
public class ArticleSheetEntry extends javax.swing.JFrame {
    private Article article;
    /**
     * Creates new form Article
     */
    public ArticleSheetEntry() {
        try {
        UIManager.setLookAndFeel(new FlatDarkLaf());

        
        
    } catch (Exception ex) {
        Logger.getLogger(AdvancedSearchConsult.class.getName()).log(Level.SEVERE, null, ex);
    }
        initComponents();
        // You can initialize the text fields with default values or leave them empty
        int windowWidth = 1130; // Adjust the desired width
        int windowHeight = 659; // Adjust the desired height
        setSize(windowWidth, windowHeight);
        setResizable(false); // Prevent resizing
        setLocationRelativeTo(null);
    }
    public ArticleSheetEntry(Article article) {
               try {
        UIManager.setLookAndFeel(new FlatDarkLaf());

        
        
    } catch (Exception ex) {
        Logger.getLogger(AdvancedSearchConsult.class.getName()).log(Level.SEVERE, null, ex);
    }
        initComponents();
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = toolkit.getScreenSize();
        int screenWidth = screenSize.width;
        int screenHeight = screenSize.height;

        int windowWidth = (int) (screenWidth * 0.8);
        int windowHeight = (int) (screenHeight * 0.8);
        setSize(windowWidth, windowHeight);
        setLocationRelativeTo(null);
        articles = new ArrayList<Article>();
        // Populate the text fields with the article's data
        classTextField.setText(article.getCodeClass());
        articleCodeTextField.setText(article.getCodeArt());
        desigTextField.setText(article.getDesigArt());
        mesureUTextField.setText(article.getUniteMes());
        stockQTextField.setText(String.valueOf(article.getQteSt()));
        shelfTextField.setText(article.getCasier());
        observTextField.setText(article.getObservation());
        deadToggleButton.setText(article.isMort() ? "Yes" : "No");
        dormantToggleButton.setText(article.isDormant() ? "Yes" : "No");
        activeToggleButton.setText(article.isActif() ? "Yes" : "No");
        aisleTextField.setText(article.getRayon());
        stockMinTextField.setText(String.valueOf(article.getStockMini()));
        stockMaxTextField.setText(String.valueOf(article.getStockMax()));
        stockSecTextField.setText(String.valueOf(article.getStockSecu()));
        valueTextField.setText(String.valueOf(article.getValeur()));
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        mainPanel = new javax.swing.JPanel();
        classLabel = new javax.swing.JLabel();
        articleCodeLabel = new javax.swing.JLabel();
        classTextField = new javax.swing.JTextField();
        articleCodeTextField = new javax.swing.JTextField();
        desigLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        observTextField = new javax.swing.JTextArea();
        measureULabel = new javax.swing.JLabel();
        mesureUTextField = new javax.swing.JTextField();
        shelfLabel = new javax.swing.JLabel();
        shelfTextField = new javax.swing.JTextField();
        observLabel = new javax.swing.JLabel();
        deadLabel = new javax.swing.JLabel();
        deadToggleButton = new javax.swing.JToggleButton();
        dormantLabel = new javax.swing.JLabel();
        dormantToggleButton = new javax.swing.JToggleButton();
        activeLabel = new javax.swing.JLabel();
        activeToggleButton = new javax.swing.JToggleButton();
        aisleLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        stockQLabel = new javax.swing.JLabel();
        stockQTextField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        valueLabel = new javax.swing.JLabel();
        valueTextField = new javax.swing.JTextField();
        stockMinLabel = new javax.swing.JLabel();
        stockMinTextField = new javax.swing.JTextField();
        stockMaxTextField = new javax.swing.JTextField();
        stockMaxLabel = new javax.swing.JLabel();
        stockSecLabel = new javax.swing.JLabel();
        stockSecTextField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        goToFirstButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        lastButton = new javax.swing.JButton();
        goToLastButton = new javax.swing.JButton();
        changeButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        sheetLogo = new javax.swing.JLabel();
        articleSheetLabel = new javax.swing.JLabel();
        aisleTextField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        desigTextField = new javax.swing.JTextArea();
        gotoSeachButton = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        mainPanel.setBackground(new java.awt.Color(51, 51, 51));

        classLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 14)); // NOI18N
        classLabel.setForeground(new java.awt.Color(255, 255, 255));
        classLabel.setText("Class");

        articleCodeLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 14)); // NOI18N
        articleCodeLabel.setForeground(new java.awt.Color(255, 255, 255));
        articleCodeLabel.setText("Article Code");

        classTextField.setBackground(new java.awt.Color(102, 102, 102));
        classTextField.setForeground(new java.awt.Color(255, 255, 255));
        classTextField.setText("245");
        classTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 102)));
        classTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classTextFieldActionPerformed(evt);
            }
        });

        articleCodeTextField.setBackground(new java.awt.Color(102, 102, 102));
        articleCodeTextField.setForeground(new java.awt.Color(255, 255, 255));
        articleCodeTextField.setText("245");
        articleCodeTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 102)));
        articleCodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                articleCodeTextFieldActionPerformed(evt);
            }
        });

        desigLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 14)); // NOI18N
        desigLabel.setForeground(new java.awt.Color(255, 255, 255));
        desigLabel.setText("Designation");

        observTextField.setBackground(new java.awt.Color(102, 102, 102));
        observTextField.setColumns(20);
        observTextField.setForeground(new java.awt.Color(255, 255, 255));
        observTextField.setRows(5);
        observTextField.setBorder(null);
        jScrollPane1.setViewportView(observTextField);

        measureULabel.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 14)); // NOI18N
        measureULabel.setForeground(new java.awt.Color(255, 255, 255));
        measureULabel.setText("Mesure Unit");

        mesureUTextField.setBackground(new java.awt.Color(102, 102, 102));
        mesureUTextField.setForeground(new java.awt.Color(255, 255, 255));
        mesureUTextField.setText("N");
        mesureUTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 102)));
        mesureUTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesureUTextFieldActionPerformed(evt);
            }
        });

        shelfLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 14)); // NOI18N
        shelfLabel.setForeground(new java.awt.Color(255, 255, 255));
        shelfLabel.setText("Shelf");

        shelfTextField.setBackground(new java.awt.Color(102, 102, 102));
        shelfTextField.setForeground(new java.awt.Color(255, 255, 255));
        shelfTextField.setText("012A2");
        shelfTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 102)));
        shelfTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shelfTextFieldActionPerformed(evt);
            }
        });

        observLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 14)); // NOI18N
        observLabel.setForeground(new java.awt.Color(255, 255, 255));
        observLabel.setText("Observation");

        deadLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 14)); // NOI18N
        deadLabel.setForeground(new java.awt.Color(255, 255, 255));
        deadLabel.setText("Dead");

        deadToggleButton.setBackground(new java.awt.Color(102, 102, 102));
        deadToggleButton.setForeground(new java.awt.Color(255, 255, 255));
        deadToggleButton.setText("No");
        deadToggleButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 102)));
        deadToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deadToggleButtonActionPerformed(evt);
            }
        });

        dormantLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 14)); // NOI18N
        dormantLabel.setForeground(new java.awt.Color(255, 255, 255));
        dormantLabel.setText("Dormant");

        dormantToggleButton.setBackground(new java.awt.Color(102, 102, 102));
        dormantToggleButton.setForeground(new java.awt.Color(255, 255, 255));
        dormantToggleButton.setText("No");
        dormantToggleButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 102)));
        dormantToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dormantToggleButtonActionPerformed(evt);
            }
        });

        activeLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 14)); // NOI18N
        activeLabel.setForeground(new java.awt.Color(255, 255, 255));
        activeLabel.setText("Active");

        activeToggleButton.setBackground(new java.awt.Color(102, 102, 102));
        activeToggleButton.setForeground(new java.awt.Color(255, 255, 255));
        activeToggleButton.setText("No");
        activeToggleButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 102)));
        activeToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activeToggleButtonActionPerformed(evt);
            }
        });

        aisleLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 14)); // NOI18N
        aisleLabel.setForeground(new java.awt.Color(255, 255, 255));
        aisleLabel.setText("Aisle");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        stockQLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 14)); // NOI18N
        stockQLabel.setForeground(new java.awt.Color(255, 255, 255));
        stockQLabel.setText("Stock Quantity");

        stockQTextField.setBackground(new java.awt.Color(102, 102, 102));
        stockQTextField.setForeground(new java.awt.Color(255, 255, 255));
        stockQTextField.setText("245");
        stockQTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 102)));
        stockQTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockQTextFieldActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        valueLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 14)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(255, 255, 255));
        valueLabel.setText("value");

        valueTextField.setBackground(new java.awt.Color(102, 102, 102));
        valueTextField.setForeground(new java.awt.Color(255, 255, 255));
        valueTextField.setText("245");
        valueTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 102)));
        valueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueTextFieldActionPerformed(evt);
            }
        });

        stockMinLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 14)); // NOI18N
        stockMinLabel.setForeground(new java.awt.Color(255, 255, 255));
        stockMinLabel.setText("Stock Min");

        stockMinTextField.setBackground(new java.awt.Color(102, 102, 102));
        stockMinTextField.setForeground(new java.awt.Color(255, 255, 255));
        stockMinTextField.setText("01");
        stockMinTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 102)));
        stockMinTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockMinTextFieldActionPerformed(evt);
            }
        });

        stockMaxTextField.setBackground(new java.awt.Color(102, 102, 102));
        stockMaxTextField.setForeground(new java.awt.Color(255, 255, 255));
        stockMaxTextField.setText("245");
        stockMaxTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 102)));
        stockMaxTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockMaxTextFieldActionPerformed(evt);
            }
        });

        stockMaxLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 14)); // NOI18N
        stockMaxLabel.setForeground(new java.awt.Color(255, 255, 255));
        stockMaxLabel.setText("Stock Max");

        stockSecLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 14)); // NOI18N
        stockSecLabel.setForeground(new java.awt.Color(255, 255, 255));
        stockSecLabel.setText("Stock Secure");

        stockSecTextField.setBackground(new java.awt.Color(102, 102, 102));
        stockSecTextField.setForeground(new java.awt.Color(255, 255, 255));
        stockSecTextField.setText("245");
        stockSecTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 102)));
        stockSecTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockSecTextFieldActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));

        goToFirstButton.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 16)); // NOI18N
        goToFirstButton.setForeground(new java.awt.Color(255, 255, 255));
        goToFirstButton.setText("Go to First");
        goToFirstButton.setBorder(null);
        goToFirstButton.setContentAreaFilled(false);
        goToFirstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToFirstButtonActionPerformed(evt);
            }
        });

        nextButton.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 16)); // NOI18N
        nextButton.setForeground(new java.awt.Color(255, 255, 255));
        nextButton.setText("Next>>");
        nextButton.setBorder(null);
        nextButton.setContentAreaFilled(false);
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        lastButton.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 16)); // NOI18N
        lastButton.setForeground(new java.awt.Color(255, 255, 255));
        lastButton.setText("<<Last");
        lastButton.setBorder(null);
        lastButton.setContentAreaFilled(false);

        goToLastButton.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 16)); // NOI18N
        goToLastButton.setForeground(new java.awt.Color(255, 255, 255));
        goToLastButton.setText("Go to Last");
        goToLastButton.setBorder(null);
        goToLastButton.setContentAreaFilled(false);
        goToLastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToLastButtonActionPerformed(evt);
            }
        });

        changeButton.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 16)); // NOI18N
        changeButton.setForeground(new java.awt.Color(255, 255, 255));
        changeButton.setText("Change");
        changeButton.setBorder(null);
        changeButton.setContentAreaFilled(false);
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(255, 102, 0));
        cancelButton.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 16)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.setBorder(null);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(0, 51, 102));
        saveButton.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 16)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Save");
        saveButton.setBorder(null);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        sheetLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sheet_logo.png"))); // NOI18N

        articleSheetLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 1, 36)); // NOI18N
        articleSheetLabel.setForeground(new java.awt.Color(153, 153, 153));
        articleSheetLabel.setText("Article Sheet");

        aisleTextField.setBackground(new java.awt.Color(102, 102, 102));
        aisleTextField.setForeground(new java.awt.Color(255, 255, 255));
        aisleTextField.setText("01");
        aisleTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 102)));
        aisleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aisleTextFieldActionPerformed(evt);
            }
        });

        desigTextField.setBackground(new java.awt.Color(102, 102, 102));
        desigTextField.setColumns(20);
        desigTextField.setForeground(new java.awt.Color(255, 255, 255));
        desigTextField.setRows(5);
        desigTextField.setBorder(null);
        jScrollPane3.setViewportView(desigTextField);

        gotoSeachButton.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 16)); // NOI18N
        gotoSeachButton.setText("Search");
        gotoSeachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoSeachButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(mainPanelLayout.createSequentialGroup()
                                                    .addGap(25, 25, 25)
                                                    .addComponent(valueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addComponent(stockQLabel))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(stockQTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                                .addComponent(valueTextField))
                                            .addGap(18, 18, 18)
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(mainPanelLayout.createSequentialGroup()
                                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(stockMinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(stockMaxLabel, javax.swing.GroupLayout.Alignment.LEADING))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(stockMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(stockMaxTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(mainPanelLayout.createSequentialGroup()
                                                    .addComponent(stockSecLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(stockSecTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(108, 108, 108)
                                            .addComponent(measureULabel)
                                            .addGap(30, 30, 30)
                                            .addComponent(mesureUTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(goToFirstButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lastButton)
                                        .addGap(52, 52, 52)
                                        .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57)
                                        .addComponent(goToLastButton)
                                        .addGap(72, 72, 72)
                                        .addComponent(changeButton)
                                        .addGap(298, 298, 298)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(sheetLogo)
                                .addGap(18, 18, 18)
                                .addComponent(articleSheetLabel)
                                .addGap(205, 205, 205)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 76, Short.MAX_VALUE)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(classLabel)
                            .addComponent(articleCodeLabel)
                            .addComponent(desigLabel)
                            .addComponent(shelfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(observLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(articleCodeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                    .addComponent(shelfTextField))
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGap(222, 222, 222)
                                        .addComponent(aisleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(aisleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(deadLabel))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(dormantLabel)
                                            .addComponent(activeLabel))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dormantToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(activeToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deadToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(85, 85, 85))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(classTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(gotoSeachButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(gotoSeachButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(articleSheetLabel)
                            .addComponent(sheetLogo))
                        .addGap(68, 68, 68)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(desigLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(observLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addComponent(articleCodeLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(activeToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(activeLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(dormantToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dormantLabel))
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(shelfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(deadToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(deadLabel)))))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(classTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(classLabel))
                                        .addGap(18, 18, 18)
                                        .addComponent(articleCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(shelfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(aisleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(aisleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(mesureUTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(measureULabel)
                                            .addComponent(stockQTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(stockQLabel)
                                            .addComponent(stockMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(stockMinLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(valueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(valueLabel))
                                            .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(stockMaxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(stockMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(14, 14, 14)
                                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(stockSecTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(stockSecLabel)))))
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(goToLastButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(changeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(goToFirstButton)
                                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(433, Short.MAX_VALUE))))))
        );

        getContentPane().add(mainPanel);
        mainPanel.setBounds(0, 0, 1130, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stockSecTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockSecTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockSecTextFieldActionPerformed

    private void stockMaxTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockMaxTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockMaxTextFieldActionPerformed

    private void stockMinTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockMinTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockMinTextFieldActionPerformed

    private void valueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueTextFieldActionPerformed

    private void stockQTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockQTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockQTextFieldActionPerformed

    private void activeToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activeToggleButtonActionPerformed

    private void dormantToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dormantToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dormantToggleButtonActionPerformed

    private void deadToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deadToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deadToggleButtonActionPerformed

    private void shelfTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shelfTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shelfTextFieldActionPerformed

    private void mesureUTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesureUTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesureUTextFieldActionPerformed

    private void articleCodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_articleCodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_articleCodeTextFieldActionPerformed

    private void classTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classTextFieldActionPerformed
    private int currentIndex = 0;
    private List<Article> articles;
    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
    try {
        if (articles == null || articles.isEmpty()) {
            // Retrieve all articles from the database
            articles = DataBaseUtils.getAllArticles();
            currentIndex = 0;
        }

        if (articles != null && !articles.isEmpty()) {
            currentIndex++;
            if (currentIndex >= articles.size()) {
                currentIndex = 0; // Wrap around to the first article
            }

            // Populate the text fields with the next article's data
            Article nextArticle = articles.get(currentIndex);
            classTextField.setText(nextArticle.getCodeClass());
            articleCodeTextField.setText(nextArticle.getCodeArt());
            desigTextField.setText(nextArticle.getDesigArt());
            mesureUTextField.setText(nextArticle.getUniteMes());
            stockQTextField.setText(String.valueOf(nextArticle.getQteSt()));
            shelfTextField.setText(nextArticle.getCasier());
            observTextField.setText(nextArticle.getObservation());
            deadToggleButton.setText(nextArticle.isMort() ? "Yes" : "No");
            dormantToggleButton.setText(nextArticle.isDormant() ? "Yes" : "No");
            activeToggleButton.setText(nextArticle.isActif() ? "Yes" : "No");
            aisleTextField.setText(nextArticle.getRayon());
            stockMinTextField.setText(String.valueOf(nextArticle.getStockMini()));
            stockMaxTextField.setText(String.valueOf(nextArticle.getStockMax()));
            stockSecTextField.setText(String.valueOf(nextArticle.getStockSecu()));
            valueTextField.setText(String.valueOf(nextArticle.getValeur()));
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void goToLastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToLastButtonActionPerformed
        // TODO add your handling code here:
    try {
        if (articles == null || articles.isEmpty()) {
            // Retrieve all articles from the database
            articles = DataBaseUtils.getAllArticles();
        }

        if (articles != null && !articles.isEmpty()) {
            // Get the last article in the list
            Article lastArticle = articles.get(articles.size() - 1);

            // Populate the text fields with the last article's data
            classTextField.setText(lastArticle.getCodeClass());
            articleCodeTextField.setText(lastArticle.getCodeArt());
            desigTextField.setText(lastArticle.getDesigArt());
            mesureUTextField.setText(lastArticle.getUniteMes());
            stockQTextField.setText(String.valueOf(lastArticle.getQteSt()));
            shelfTextField.setText(lastArticle.getCasier());
            observTextField.setText(lastArticle.getObservation());
            deadToggleButton.setText(lastArticle.isMort() ? "Yes" : "No");
            dormantToggleButton.setText(lastArticle.isDormant() ? "Yes" : "No");
            activeToggleButton.setText(lastArticle.isActif() ? "Yes" : "No");
            aisleTextField.setText(lastArticle.getRayon());
            stockMinTextField.setText(String.valueOf(lastArticle.getStockMini()));
            stockMaxTextField.setText(String.valueOf(lastArticle.getStockMax()));
            stockSecTextField.setText(String.valueOf(lastArticle.getStockSecu()));
            valueTextField.setText(String.valueOf(lastArticle.getValeur()));
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    }    
    }//GEN-LAST:event_goToLastButtonActionPerformed

    private void goToFirstButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToFirstButtonActionPerformed
        // TODO add your handling code here:
    try {
        if (articles == null || articles.isEmpty()) {
            // Retrieve all articles from the database
            articles = DataBaseUtils.getAllArticles();
        }

        if (articles != null && !articles.isEmpty()) {
            // Get the first article in the list
            Article firstArticle = articles.get(0);

            // Populate the text fields with the first article's data
            classTextField.setText(firstArticle.getCodeClass());
            articleCodeTextField.setText(firstArticle.getCodeArt());
            desigTextField.setText(firstArticle.getDesigArt());
            mesureUTextField.setText(firstArticle.getUniteMes());
            stockQTextField.setText(String.valueOf(firstArticle.getQteSt()));
            shelfTextField.setText(firstArticle.getCasier());
            observTextField.setText(firstArticle.getObservation());
            deadToggleButton.setText(firstArticle.isMort() ? "Yes" : "No");
            dormantToggleButton.setText(firstArticle.isDormant() ? "Yes" : "No");
            activeToggleButton.setText(firstArticle.isActif() ? "Yes" : "No");
            aisleTextField.setText(firstArticle.getRayon());
            stockMinTextField.setText(String.valueOf(firstArticle.getStockMini()));
            stockMaxTextField.setText(String.valueOf(firstArticle.getStockMax()));
            stockSecTextField.setText(String.valueOf(firstArticle.getStockSecu()));
            valueTextField.setText(String.valueOf(firstArticle.getValeur()));
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_goToFirstButtonActionPerformed
//    private Article getCurrentArticle() {
////        Article currentArticle = new Article();
////        currentArticle.setCodeClass(classTextField.getText());
////        currentArticle.setCodeArt(articleCodeTextField.getText());
////        currentArticle.setDesigArt(observTextField.getText());
////        currentArticle.setUniteMes(mesureUTextField.getText());
////        currentArticle.setQteSt(Double.parseDouble(stockQTextField.getText()));
////        currentArticle.setCasier(shelfTextField.getText());
////        currentArticle.setObservation(observTextField.getText());
////        currentArticle.setMort(deadToggleButton.getText().equalsIgnoreCase("Yes"));
////        currentArticle.setDormant(dormantToggleButton.getText().equalsIgnoreCase("Yes"));
////        currentArticle.setActif(activeToggleButton.getText().equalsIgnoreCase("Yes"));
////        currentArticle.setRayon(aisleTextField.getText());
////        currentArticle.setStockMini(Double.parseDouble(stockMinTextField.getText()));
////        currentArticle.setStockMax(Double.parseDouble(stockMaxTextField.getText()));
////        currentArticle.setStockSecu(Double.parseDouble(stockSecTextField.getText()));
////        currentArticle.setValeur(Double.parseDouble(valueTextField.getText()));
////        return currentArticle;
//}


    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        // TODO add your handling code here:
//        try {
//        // Get the currently selected article from the list
//        int selectedIndex = articles.indexOf(getCurrentArticle());
//        if (selectedIndex >= 0) {
//            // Update the selected article with the values from the text fields
//            Article selectedArticle = articles.get(selectedIndex);
//            selectedArticle.setCodeClass(classTextField.getText());
//            selectedArticle.setCodeArt(articleCodeTextField.getText());
//            selectedArticle.setDesigArt(observTextField.getText());
//            selectedArticle.setUniteMes(mesureUTextField.getText());
//            selectedArticle.setQteSt(Double.parseDouble(stockQTextField.getText()));
//            selectedArticle.setCasier(shelfTextField.getText());
//            selectedArticle.setObservation(observTextField.getText());
//            selectedArticle.setMort(deadToggleButton.getText().equalsIgnoreCase("Yes"));
//            selectedArticle.setDormant(dormantToggleButton.getText().equalsIgnoreCase("Yes"));
//            selectedArticle.setActif(activeToggleButton.getText().equalsIgnoreCase("Yes"));
//            selectedArticle.setRayon(aisleTextField.getText());
//            selectedArticle.setStockMini(Double.parseDouble(stockMinTextField.getText()));
//            selectedArticle.setStockMax(Double.parseDouble(stockMaxTextField.getText()));
//            selectedArticle.setStockSecu(Double.parseDouble(stockSecTextField.getText()));
//            selectedArticle.setValeur(Double.parseDouble(valueTextField.getText()));
//        }
//    } catch (NumberFormatException ex) {
//        // Handle any errors in parsing the numeric values
//        JOptionPane.showMessageDialog(this, "Please enter valid numeric values.", "Error", JOptionPane.ERROR_MESSAGE);
//    }

    }//GEN-LAST:event_changeButtonActionPerformed
//
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
//    try {
//        // Save the new or modified articles to the database
//        for (Article article : articles) {
//            Article existingArticle = DataBaseUtils.getArticleById(article.getCodeArt());
//            if (existingArticle == null) {
//                // New article, insert it into the database
//                DataBaseUtils.insertArticle(article);
//            } else {
//                // Existing article, update it in the database
//                updateArticleInDatabase(article, existingArticle);
//            }
//        }
//
//        // Clear the text fields
//        clearTextFields();
//    } catch (SQLException ex) {
//        // Handle any SQL exceptions
//        JOptionPane.showMessageDialog(this, "Error saving article: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//    }
    }//GEN-LAST:event_saveButtonActionPerformed
//    private void updateArticleInDatabase(Article newArticle, Article existingArticle) throws SQLException {
//        // Update the existing article with the new values
//        existingArticle.setDesigArt(newArticle.getDesigArt());
//        existingArticle.setCodeClass(newArticle.getCodeClass());
//        existingArticle.setUniteMes(newArticle.getUniteMes());
//        existingArticle.setQteSt(newArticle.getQteSt());
//        existingArticle.setCasier(newArticle.getCasier());
//        existingArticle.setStockMini(newArticle.getStockMini());
//        existingArticle.setStockMax(newArticle.getStockMax());
//        existingArticle.setStockSecu(newArticle.getStockSecu());
//        existingArticle.setValeur(newArticle.getValeur());
//        existingArticle.setMort(newArticle.isMort());
//        existingArticle.setObservation(newArticle.getObservation());
//        existingArticle.setRayon(newArticle.getRayon());
//        existingArticle.setDormant(newArticle.isDormant());
//        existingArticle.setActif(newArticle.isActif());
//
//        // Update the article in the database
//        DataBaseUtils.updateArticle(existingArticle);
//}
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        DashboardEntry db = new DashboardEntry();
        db.setVisible(true);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void aisleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aisleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aisleTextFieldActionPerformed

    private void gotoSeachButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoSeachButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        AdvancedSearchConsult as = new AdvancedSearchConsult();
        as.setVisible(true);
    }//GEN-LAST:event_gotoSeachButtonActionPerformed
    private void clearTextFields() {
        // Code to clear all the text fields
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArticleSheetEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArticleSheetEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArticleSheetEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArticleSheetEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArticleSheetEntry().setVisible(true);
            }
        });
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activeLabel;
    private javax.swing.JToggleButton activeToggleButton;
    private javax.swing.JLabel aisleLabel;
    private javax.swing.JTextField aisleTextField;
    private javax.swing.JLabel articleCodeLabel;
    private javax.swing.JTextField articleCodeTextField;
    private javax.swing.JLabel articleSheetLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton changeButton;
    private javax.swing.JLabel classLabel;
    private javax.swing.JTextField classTextField;
    private javax.swing.JLabel deadLabel;
    private javax.swing.JToggleButton deadToggleButton;
    private javax.swing.JLabel desigLabel;
    private javax.swing.JTextArea desigTextField;
    private javax.swing.JLabel dormantLabel;
    private javax.swing.JToggleButton dormantToggleButton;
    private javax.swing.JButton goToFirstButton;
    private javax.swing.JButton goToLastButton;
    private javax.swing.JButton gotoSeachButton;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton lastButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel measureULabel;
    private javax.swing.JTextField mesureUTextField;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel observLabel;
    private javax.swing.JTextArea observTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel sheetLogo;
    private javax.swing.JLabel shelfLabel;
    private javax.swing.JTextField shelfTextField;
    private javax.swing.JLabel stockMaxLabel;
    private javax.swing.JTextField stockMaxTextField;
    private javax.swing.JLabel stockMinLabel;
    private javax.swing.JTextField stockMinTextField;
    private javax.swing.JLabel stockQLabel;
    private javax.swing.JTextField stockQTextField;
    private javax.swing.JLabel stockSecLabel;
    private javax.swing.JTextField stockSecTextField;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTextField valueTextField;
    // End of variables declaration//GEN-END:variables
}
