package com.mycompany.warehouse_management;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;


//import com.apache.commons.dbutils.DbUtils; // Assuming you're using DbUtils for resultSetToTableModel

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lyeschl
 */
public class DashboardAdmin extends javax.swing.JFrame {
    private CustomPanel customPanel;
    /**
     * Creates new form Dashboard
     */

    public DashboardAdmin() {
        try {
        UIManager.setLookAndFeel(new FlatDarkLaf());

        
        
    } catch (Exception ex) {
        Logger.getLogger(AdvancedSearch.class.getName()).log(Level.SEVERE, null, ex);
    }
        initComponents();
        int windowWidth = 1130; // Adjust the desired width
        int windowHeight = 659; // Adjust the desired height
        setSize(windowWidth, windowHeight);
        setResizable(false); // Prevent resizing
        setLocationRelativeTo(null); // Center the window
        DataBaseUtils.populateArticleTableWithoutSearch(articleTable);
        DataBaseUtils.populateMoveTable(movesTable);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu2 = new javax.swing.JPopupMenu();
        exitTicketOption = new javax.swing.JMenuItem();
        returnTicketOption = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        accountSettingsButton = new javax.swing.JToggleButton();
        accountSettingsButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        movesTable = new javax.swing.JTable();
        movesLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        articleTable = new javax.swing.JTable();
        articlesLabel = new javax.swing.JLabel();
        newMove = new javax.swing.JToggleButton();
        dashboardLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        logoLabel1 = new javax.swing.JLabel();
        dashboardLogo = new javax.swing.JLabel();
        totalUsersLabel = new javax.swing.JLabel();
        totalExitsLabel = new javax.swing.JLabel();
        totalReturnsLabel = new javax.swing.JLabel();
        backgroundImageLabel = new javax.swing.JLabel();

        exitTicketOption.setText("Exit Ticket");
        exitTicketOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTicketOptionMouseClicked(evt);
            }
        });

        returnTicketOption.setText("Return Ticket");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        accountSettingsButton.setBackground(new java.awt.Color(51, 51, 51));
        accountSettingsButton.setFont(new java.awt.Font("POI Aeronaut Trial", 1, 14)); // NOI18N
        accountSettingsButton.setForeground(new java.awt.Color(153, 153, 153));
        accountSettingsButton.setText("Manage User Accounts");
        accountSettingsButton.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 102)));
        accountSettingsButton.setContentAreaFilled(false);
        accountSettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountSettingsButtonActionPerformed(evt);
            }
        });

        accountSettingsButton1.setBackground(new java.awt.Color(51, 51, 51));
        accountSettingsButton1.setFont(new java.awt.Font("POI Aeronaut Trial", 1, 14)); // NOI18N
        accountSettingsButton1.setForeground(new java.awt.Color(153, 153, 153));
        accountSettingsButton1.setText("Account");
        accountSettingsButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 102)));
        accountSettingsButton1.setContentAreaFilled(false);
        accountSettingsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountSettingsButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accountSettingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(accountSettingsButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(accountSettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(493, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(495, Short.MAX_VALUE)
                    .addComponent(accountSettingsButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(910, 40, 200, 560);

        movesTable.setForeground(new java.awt.Color(153, 204, 255));
        movesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        movesTable.setGridColor(new java.awt.Color(51, 102, 255));
        movesTable.setSelectionBackground(new java.awt.Color(102, 153, 255));
        movesTable.setSelectionForeground(new java.awt.Color(102, 102, 255));
        jScrollPane1.setViewportView(movesTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 180, 370, 170);

        movesLabel.setBackground(new java.awt.Color(255, 255, 255));
        movesLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 1, 18)); // NOI18N
        movesLabel.setForeground(new java.awt.Color(255, 255, 255));
        movesLabel.setText("User Accounts");
        getContentPane().add(movesLabel);
        movesLabel.setBounds(30, 144, 130, 20);

        articleTable.setForeground(new java.awt.Color(153, 204, 255));
        articleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        articleTable.setGridColor(new java.awt.Color(51, 102, 255));
        articleTable.setSelectionBackground(new java.awt.Color(102, 153, 255));
        articleTable.setSelectionForeground(new java.awt.Color(102, 102, 255));
        articleTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                articleTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(articleTable);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(20, 400, 370, 150);

        articlesLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 1, 18)); // NOI18N
        articlesLabel.setForeground(new java.awt.Color(255, 255, 255));
        articlesLabel.setText("Articles");
        getContentPane().add(articlesLabel);
        articlesLabel.setBounds(20, 360, 60, 30);

        newMove.setBackground(new java.awt.Color(51, 51, 51));
        newMove.setFont(new java.awt.Font("POI Aeronaut Trial", 1, 14)); // NOI18N
        newMove.setForeground(new java.awt.Color(153, 153, 153));
        newMove.setText("New User +");
        newMove.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 102)));
        newMove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newMoveMousePressed(evt);
            }
        });
        newMove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMoveActionPerformed(evt);
            }
        });
        getContentPane().add(newMove);
        newMove.setBounds(20, 80, 110, 40);

        dashboardLabel.setBackground(new java.awt.Color(255, 255, 255));
        dashboardLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 1, 36)); // NOI18N
        dashboardLabel.setForeground(new java.awt.Color(255, 255, 255));
        dashboardLabel.setText("Dashboard");
        getContentPane().add(dashboardLabel);
        dashboardLabel.setBounds(50, 10, 190, 40);

        welcomeLabel.setBackground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 1, 36)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setText("Welcome");
        getContentPane().add(welcomeLabel);
        welcomeLabel.setBounds(390, 10, 170, 40);

        logoLabel1.setBackground(new java.awt.Color(255, 255, 255));
        logoLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/output-onlinepngtools(1).png"))); // NOI18N
        getContentPane().add(logoLabel1);
        logoLabel1.setBounds(20, 590, 60, 65);

        dashboardLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard_icon.png"))); // NOI18N
        getContentPane().add(dashboardLogo);
        dashboardLogo.setBounds(10, 10, 30, 30);

        totalUsersLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 16)); // NOI18N
        int totalUsers = DataBaseUtils.getTotalUsers();
        totalUsersLabel.setText("Total Users: " + totalUsers);
        getContentPane().add(totalUsersLabel);
        totalUsersLabel.setBounds(390, 60, 140, 30);

        int totalExits = DataBaseUtils.getTotalExits();
        totalExitsLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 16)); // NOI18N
        totalExitsLabel.setText("Total Active Accounts: " + totalExits);
        getContentPane().add(totalExitsLabel);
        totalExitsLabel.setBounds(530, 60, 160, 30);

        int totalReturns = DataBaseUtils.getTotalReturns();
        totalReturnsLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 16)); // NOI18N
        totalReturnsLabel.setText("Total Inactive Accounts: " + totalReturns);
        getContentPane().add(totalReturnsLabel);
        totalReturnsLabel.setBounds(710, 60, 170, 30);

        backgroundImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sunset-gradient-hd-wallpaper(1).png"))); // NOI18N
        backgroundImageLabel.setText("jLabel1");
        getContentPane().add(backgroundImageLabel);
        backgroundImageLabel.setBounds(0, 0, 1340, 760);
        // Remove the backgroundImageLabel
        getContentPane().remove(backgroundImageLabel);

        // Create and add the CustomPanel
        customPanel = new CustomPanel();
        customPanel.setBounds(0, 0, 1340, 760);
        getContentPane().add(customPanel);
        customPanel.setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitTicketOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTicketOptionMouseClicked
        // TODO add your handling code here:
        dispose();
        ExitTicket eti = new ExitTicket();
        eti.setVisible(true);
    }//GEN-LAST:event_exitTicketOptionMouseClicked

    private void newMoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newMoveActionPerformed

    private void newMoveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newMoveMousePressed
        // TODO add your handling code here:
        jPopupMenu2.show(newMove, 0, newMove.getHeight());
    }//GEN-LAST:event_newMoveMousePressed

    private void accountSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountSettingsButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        AccountSettings as = new AccountSettings();
        as.setVisible(true);
    }//GEN-LAST:event_accountSettingsButtonActionPerformed

    private void articleTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_articleTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_articleTableMouseClicked

    private void accountSettingsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountSettingsButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountSettingsButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdmin().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton accountSettingsButton;
    private javax.swing.JToggleButton accountSettingsButton1;
    private javax.swing.JTable articleTable;
    private javax.swing.JLabel articlesLabel;
    private javax.swing.JLabel backgroundImageLabel;
    private javax.swing.JLabel dashboardLabel;
    private javax.swing.JLabel dashboardLogo;
    private javax.swing.JMenuItem exitTicketOption;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel logoLabel1;
    private javax.swing.JLabel movesLabel;
    private javax.swing.JTable movesTable;
    private javax.swing.JToggleButton newMove;
    private javax.swing.JMenuItem returnTicketOption;
    private javax.swing.JLabel totalExitsLabel;
    private javax.swing.JLabel totalReturnsLabel;
    private javax.swing.JLabel totalUsersLabel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
