/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.warehouse_management;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;

/**
 *
 * @author lyeschl
 */
public class ReturnTicket extends javax.swing.JFrame {

    /**
     * Creates new form ReturnTicket
     */
    public ReturnTicket() {
        initComponents();
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = toolkit.getScreenSize();
        int screenWidth = screenSize.width;
        int screenHeight = screenSize.height;

        int windowWidth = (int) (screenWidth * 0.8);
        int windowHeight = (int) (screenHeight * 0.8);
        setSize(windowWidth, windowHeight);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exitTicketLabel = new javax.swing.JLabel();
        returnDateLabel = new javax.swing.JLabel();
        returnDateFormattedTextField = new javax.swing.JFormattedTextField();
        brsLabel = new javax.swing.JLabel();
        brsTextField = new javax.swing.JTextField();
        natureLabel = new javax.swing.JLabel();
        natureComboBox = new javax.swing.JComboBox<>();
        desigLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        desigTextArea = new javax.swing.JTextArea();
        articlesLabel = new javax.swing.JLabel();
        articlesTextField = new javax.swing.JTextField();
        pumpLabel = new javax.swing.JLabel();
        pumpTextField = new javax.swing.JTextField();
        articleCodeLabel = new javax.swing.JLabel();
        articleCodeTextField = new javax.swing.JTextField();
        logoLabel = new javax.swing.JLabel();
        printButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        exitTicketLabel.setBackground(new java.awt.Color(0, 0, 0));
        exitTicketLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 1, 24)); // NOI18N
        exitTicketLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitTicketLabel.setText("Return Ticket ");

        returnDateLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 1, 14)); // NOI18N
        returnDateLabel.setForeground(new java.awt.Color(153, 153, 153));
        returnDateLabel.setText("Return Date");

        returnDateFormattedTextField.setBackground(new java.awt.Color(51, 51, 51));
        returnDateFormattedTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 102)));
        returnDateFormattedTextField.setForeground(new java.awt.Color(255, 255, 255));
        returnDateFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        returnDateFormattedTextField.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        returnDateFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnDateFormattedTextFieldActionPerformed(evt);
            }
        });

        brsLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 1, 14)); // NOI18N
        brsLabel.setForeground(new java.awt.Color(153, 153, 153));
        brsLabel.setText("BRS");

        brsTextField.setBackground(new java.awt.Color(51, 51, 51));
        brsTextField.setForeground(new java.awt.Color(255, 255, 255));
        brsTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 102)));
        brsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brsTextFieldActionPerformed(evt);
            }
        });

        natureLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 1, 14)); // NOI18N
        natureLabel.setForeground(new java.awt.Color(153, 153, 153));
        natureLabel.setText("Nature");

        natureComboBox.setBackground(new java.awt.Color(102, 102, 102));
        natureComboBox.setForeground(new java.awt.Color(255, 255, 255));
        natureComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Garantie 2 ans", "Garantie ", "Something else", " " }));
        natureComboBox.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 102)));

        desigLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 1, 14)); // NOI18N
        desigLabel.setForeground(new java.awt.Color(153, 153, 153));
        desigLabel.setText("Designation");

        desigTextArea.setBackground(new java.awt.Color(102, 102, 102));
        desigTextArea.setColumns(20);
        desigTextArea.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        desigTextArea.setForeground(new java.awt.Color(255, 255, 255));
        desigTextArea.setRows(5);
        desigTextArea.setText("...");
        desigTextArea.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 102)));
        jScrollPane1.setViewportView(desigTextArea);

        articlesLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 1, 14)); // NOI18N
        articlesLabel.setForeground(new java.awt.Color(153, 153, 153));
        articlesLabel.setText("N* Articles");

        articlesTextField.setBackground(new java.awt.Color(51, 51, 51));
        articlesTextField.setForeground(new java.awt.Color(255, 255, 255));
        articlesTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 102)));
        articlesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                articlesTextFieldActionPerformed(evt);
            }
        });

        pumpLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 1, 14)); // NOI18N
        pumpLabel.setForeground(new java.awt.Color(153, 153, 153));
        pumpLabel.setText("Pump");

        pumpTextField.setBackground(new java.awt.Color(51, 51, 51));
        pumpTextField.setForeground(new java.awt.Color(255, 255, 255));
        pumpTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 102)));
        pumpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pumpTextFieldActionPerformed(evt);
            }
        });

        articleCodeLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 1, 14)); // NOI18N
        articleCodeLabel.setForeground(new java.awt.Color(153, 153, 153));
        articleCodeLabel.setText("Article Code");

        articleCodeTextField.setBackground(new java.awt.Color(51, 51, 51));
        articleCodeTextField.setForeground(new java.awt.Color(255, 255, 255));
        articleCodeTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 102)));
        articleCodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                articleCodeTextFieldActionPerformed(evt);
            }
        });

        logoLabel.setBackground(new java.awt.Color(255, 255, 255));
        logoLabel.setIcon(new javax.swing.ImageIcon("/run/media/lyeschl/ssd/main/load/output-onlinepngtools(1).png")); // NOI18N

        printButton.setBackground(new java.awt.Color(0, 51, 102));
        printButton.setFont(new java.awt.Font("POI Aeronaut Trial", 1, 14)); // NOI18N
        printButton.setForeground(new java.awt.Color(153, 153, 153));
        printButton.setText("Print");
        printButton.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 1, new java.awt.Color(51, 51, 51)));
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(255, 127, 0));
        cancelButton.setFont(new java.awt.Font("POI Aeronaut Trial", 1, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(153, 153, 153));
        cancelButton.setText("Cancel");
        cancelButton.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 51)));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(returnDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(returnDateFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(brsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(natureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(natureComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(506, 506, 506)
                        .addComponent(articleCodeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(articleCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(exitTicketLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(desigLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(articlesLabel)
                            .addComponent(pumpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pumpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(articlesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(356, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 95, Short.MAX_VALUE)
                    .addComponent(logoLabel)
                    .addGap(0, 920, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(exitTicketLabel)
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brsLabel)
                    .addComponent(returnDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(natureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnDateFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(natureComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(articlesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(articlesLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pumpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pumpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(articleCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(articleCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(desigLabel)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 408, Short.MAX_VALUE)
                    .addComponent(logoLabel)
                    .addGap(0, 27, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(6, 0, 1060, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnDateFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnDateFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnDateFormattedTextFieldActionPerformed

    private void brsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brsTextFieldActionPerformed

    private void articlesTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_articlesTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_articlesTextFieldActionPerformed

    private void pumpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pumpTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pumpTextFieldActionPerformed

    private void articleCodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_articleCodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_articleCodeTextFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();

        Dashboard dash = new Dashboard();
        dash.setVisible(true);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        // TODO add your handling code here:
        PDFGenerator pdfGenerator = new PDFGenerator();
    try {
        String exitDate = returnDateFormattedTextField.getText();
        String ticketCode = brsTextField.getText();
        String nature = (String) natureComboBox.getSelectedItem();
        String designation = desigTextArea.getText();
        String articles = articlesTextField.getText();
        String pump = pumpTextField.getText();
        String articleCode = articleCodeTextField.getText();

        pdfGenerator.generatePDF(exitDate, ticketCode, nature, designation, articles, pump, articleCode, "return-ticket.pdf");
        System.out.println("PDF generated successfully!");
    } catch (IOException e) {
        System.err.println("Error generating PDF: " + e.getMessage());
    }
    }//GEN-LAST:event_printButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel articleCodeLabel;
    private javax.swing.JTextField articleCodeTextField;
    private javax.swing.JLabel articlesLabel;
    private javax.swing.JTextField articlesTextField;
    private javax.swing.JLabel brsLabel;
    private javax.swing.JTextField brsTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel desigLabel;
    private javax.swing.JTextArea desigTextArea;
    private javax.swing.JLabel exitTicketLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JComboBox<String> natureComboBox;
    private javax.swing.JLabel natureLabel;
    private javax.swing.JButton printButton;
    private javax.swing.JLabel pumpLabel;
    private javax.swing.JTextField pumpTextField;
    private javax.swing.JFormattedTextField returnDateFormattedTextField;
    private javax.swing.JLabel returnDateLabel;
    // End of variables declaration//GEN-END:variables
}
