/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.warehouse_management;

import com.formdev.flatlaf.FlatDarkLaf;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lyeschl
 */
public class StockSheet extends javax.swing.JFrame {

    /**
     * Creates new form StockSheet
     */
    public StockSheet() {
        try {
        UIManager.setLookAndFeel(new FlatDarkLaf());

        
        
    } catch (Exception ex) {
        Logger.getLogger(AdvancedSearch.class.getName()).log(Level.SEVERE, null, ex);
    }
        initComponents();
        int windowWidth = 1280; // Adjust the desired width
        int windowHeight = 720; // Adjust the desired height
        setSize(windowWidth, windowHeight);
        setResizable(false); // Prevent resizing
        setLocationRelativeTo(null);
        
        DataBaseUtils.populateMoveTable(movesTable);
        movesTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
        @Override
    public void valueChanged(ListSelectionEvent event) {
        if (!event.getValueIsAdjusting()) {
            int selectedRow = movesTable.getSelectedRow();
            if (selectedRow != -1) {
                // Retrieve the values directly from the TableModel
                DefaultTableModel model = (DefaultTableModel) movesTable.getModel();
                String type = (String) model.getValueAt(selectedRow, 0);
                String num = (String) model.getValueAt(selectedRow, 1);
                String numOT = (String) model.getValueAt(selectedRow, 2);
                String codeAnal = (String) model.getValueAt(selectedRow, 3);
                String codeMag = (String) model.getValueAt(selectedRow, 4);
                String codeUnit = (String) model.getValueAt(selectedRow, 5);
                Date dateSort = (Date) model.getValueAt(selectedRow, 6);
                int total = ((Number) model.getValueAt(selectedRow, 7)).intValue();
                Date dateValide = (Date) model.getValueAt(selectedRow, 8);
                String valide = (String) model.getValueAt(selectedRow, 9);
                String annule = (String) model.getValueAt(selectedRow, 10);

                // Populate the text fields
                articleCodeTextField.setText(num);
                classTextField.setText(codeAnal);
                mesureUTextField.setText(codeUnit);
                shelfTextField.setText(codeMag);
                aisleTextField.setText(numOT);
                stockMinTextField.setText(String.valueOf(total));
                stockMaxTextField.setText(valide);
            }
        }
    }
});





    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        articleCodeLabel = new javax.swing.JLabel();
        articleCodeTextField = new javax.swing.JTextField();
        classTextField = new javax.swing.JTextField();
        classLabel = new javax.swing.JLabel();
        measureULabel = new javax.swing.JLabel();
        mesureUTextField = new javax.swing.JTextField();
        shelfTextField = new javax.swing.JTextField();
        shelfLabel = new javax.swing.JLabel();
        aisleLabel = new javax.swing.JLabel();
        stockMinLabel = new javax.swing.JLabel();
        stockMaxLabel = new javax.swing.JLabel();
        stockSheetTitleLabel = new javax.swing.JLabel();
        aisleLabel1 = new javax.swing.JLabel();
        pumpTextField = new javax.swing.JTextField();
        stockMinTextField = new javax.swing.JTextField();
        stockMaxTextField = new javax.swing.JTextField();
        aisleTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        movesTable = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        articleCodeLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 16)); // NOI18N
        articleCodeLabel.setText("Article Code");

        articleCodeTextField.setBackground(new java.awt.Color(102, 102, 102));
        articleCodeTextField.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 16)); // NOI18N
        articleCodeTextField.setForeground(new java.awt.Color(255, 255, 255));
        articleCodeTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 51)));
        articleCodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                articleCodeTextFieldActionPerformed(evt);
            }
        });

        classTextField.setBackground(new java.awt.Color(102, 102, 102));
        classTextField.setForeground(new java.awt.Color(255, 255, 255));
        classTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 102)));
        classTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classTextFieldActionPerformed(evt);
            }
        });

        classLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 14)); // NOI18N
        classLabel.setForeground(new java.awt.Color(255, 255, 255));
        classLabel.setText("Class");

        measureULabel.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 14)); // NOI18N
        measureULabel.setForeground(new java.awt.Color(255, 255, 255));
        measureULabel.setText("Mesure Unit");

        mesureUTextField.setBackground(new java.awt.Color(102, 102, 102));
        mesureUTextField.setForeground(new java.awt.Color(255, 255, 255));
        mesureUTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 102)));
        mesureUTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesureUTextFieldActionPerformed(evt);
            }
        });

        shelfTextField.setBackground(new java.awt.Color(102, 102, 102));
        shelfTextField.setForeground(new java.awt.Color(255, 255, 255));
        shelfTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 102)));
        shelfTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shelfTextFieldActionPerformed(evt);
            }
        });

        shelfLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 14)); // NOI18N
        shelfLabel.setForeground(new java.awt.Color(255, 255, 255));
        shelfLabel.setText("Shelf");

        aisleLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 14)); // NOI18N
        aisleLabel.setForeground(new java.awt.Color(255, 255, 255));
        aisleLabel.setText("Aisle");

        stockMinLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 14)); // NOI18N
        stockMinLabel.setForeground(new java.awt.Color(255, 255, 255));
        stockMinLabel.setText("Stock Min");

        stockMaxLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 14)); // NOI18N
        stockMaxLabel.setForeground(new java.awt.Color(255, 255, 255));
        stockMaxLabel.setText("Stock Max");

        stockSheetTitleLabel.setFont(new java.awt.Font("POI Aeronaut Trial", 1, 36)); // NOI18N
        stockSheetTitleLabel.setText("Stock Sheet");

        aisleLabel1.setFont(new java.awt.Font("POI Aeronaut Trial", 0, 14)); // NOI18N
        aisleLabel1.setForeground(new java.awt.Color(255, 255, 255));
        aisleLabel1.setText("PUMP");

        pumpTextField.setBackground(new java.awt.Color(102, 102, 102));
        pumpTextField.setForeground(new java.awt.Color(255, 255, 255));
        pumpTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 102)));
        pumpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pumpTextFieldActionPerformed(evt);
            }
        });

        stockMinTextField.setBackground(new java.awt.Color(102, 102, 102));
        stockMinTextField.setForeground(new java.awt.Color(255, 255, 255));
        stockMinTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 102)));
        stockMinTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockMinTextFieldActionPerformed(evt);
            }
        });

        stockMaxTextField.setBackground(new java.awt.Color(102, 102, 102));
        stockMaxTextField.setForeground(new java.awt.Color(255, 255, 255));
        stockMaxTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 102)));
        stockMaxTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockMaxTextFieldActionPerformed(evt);
            }
        });

        aisleTextField.setBackground(new java.awt.Color(102, 102, 102));
        aisleTextField.setForeground(new java.awt.Color(255, 255, 255));
        aisleTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 102)));
        aisleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aisleTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(headerPanelLayout.createSequentialGroup()
                                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(measureULabel)
                                    .addComponent(articleCodeLabel))
                                .addGap(18, 18, 18)
                                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(mesureUTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(articleCodeTextField))
                                .addGap(161, 161, 161)
                                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(classLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(shelfLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(aisleLabel1))
                        .addGap(29, 29, 29)
                        .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(headerPanelLayout.createSequentialGroup()
                                .addComponent(classTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                                .addComponent(stockMinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                                .addComponent(pumpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(stockMaxLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                                .addComponent(shelfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(aisleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(84, 84, 84)
                        .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(stockMaxTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(aisleTextField)
                            .addComponent(stockMinTextField))
                        .addGap(23, 23, 23))
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addComponent(stockSheetTitleLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mesureUTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(measureULabel))
                .addGap(11, 11, 11))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addComponent(stockSheetTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(classLabel)
                        .addComponent(classTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                            .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(stockMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(stockMinLabel))
                            .addGap(11, 11, 11))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                            .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(articleCodeLabel)
                                .addComponent(articleCodeTextField))
                            .addGap(7, 7, 7))))
                .addGap(18, 18, 18)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aisleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pumpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stockMaxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stockMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(aisleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(aisleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(shelfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(shelfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );

        // Define the column types
        java.lang.Class<?>[] columnTypes = {
            String.class, // type
            String.class, // num
            String.class, // num_OT
            String.class, // code_anal
            String.class, // code_mag
            String.class, // code_unit
            Date.class,   // date_sort
            Integer.class, // total
            Date.class,   // date_valide
            String.class, // valide
            String.class  // annule
        };
        movesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "type", "num", "num_OT", "code_anal", "code_mag", "code_unit", "date_sort", "total", "date_valide", "valide", "annule"
            }
        ) {
            @Override
            public java.lang.Class<?> getColumnClass(int columnIndex) {
                return columnTypes[columnIndex];
            }
        }
    );
    jScrollPane2.setViewportView(movesTable);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(36, 36, 36)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2))
            .addContainerGap(115, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(41, 41, 41)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(112, Short.MAX_VALUE))
    );

    getContentPane().add(jPanel1);
    jPanel1.setBounds(0, 0, 1330, 720);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void articleCodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_articleCodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_articleCodeTextFieldActionPerformed

    private void classTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classTextFieldActionPerformed

    private void mesureUTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesureUTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesureUTextFieldActionPerformed

    private void stockMinTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockMinTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockMinTextFieldActionPerformed

    private void stockMaxTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockMaxTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockMaxTextFieldActionPerformed

    private void shelfTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shelfTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shelfTextFieldActionPerformed

    private void aisleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aisleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aisleTextFieldActionPerformed

    private void pumpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pumpTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pumpTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockSheet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aisleLabel;
    private javax.swing.JLabel aisleLabel1;
    private javax.swing.JTextField aisleTextField;
    private javax.swing.JLabel articleCodeLabel;
    private javax.swing.JTextField articleCodeTextField;
    private javax.swing.JLabel classLabel;
    private javax.swing.JTextField classTextField;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel measureULabel;
    private javax.swing.JTextField mesureUTextField;
    private javax.swing.JTable movesTable;
    private javax.swing.JTextField pumpTextField;
    private javax.swing.JLabel shelfLabel;
    private javax.swing.JTextField shelfTextField;
    private javax.swing.JLabel stockMaxLabel;
    private javax.swing.JTextField stockMaxTextField;
    private javax.swing.JLabel stockMinLabel;
    private javax.swing.JTextField stockMinTextField;
    private javax.swing.JLabel stockSheetTitleLabel;
    // End of variables declaration//GEN-END:variables
}
